services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: flask
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./prediction.txt:/app/prediction.txt
      - ./reviews.txt:/app/reviews.txt
    depends_on:
      - db

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - flask

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
