"""increased text column size

Revision ID: 3956f0d58189
Revises: da61fe383731
Create Date: 2025-09-01 12:51:04.709176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3956f0d58189'
down_revision = 'da61fe383731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=False)
        batch_op.alter_column('prediction',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.alter_column('prediction',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
