"""create predict table

Revision ID: 427cab009381
Revises: ff79badc8faf
Create Date: 2025-08-26 16:55:43.720858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427cab009381'
down_revision = 'ff79badc8faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict')
    # ### end Alembic commands ###
