"""decreased text column size

Revision ID: d69d5eb7bf91
Revises: 3956f0d58189
Create Date: 2025-09-01 13:25:33.464627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd69d5eb7bf91'
down_revision = '3956f0d58189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(length=5000),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###
